### PR TITLE
Add marker and indent foldmethods

### PR DESCRIPTION
**Pull request by fedorenchik**
marker and indent foldmethods are also used, add support for them, too.

### CODE REVIEW

**Comment by Konfekt** [comment]
Thanks for the pull request! I am reluctant to merge, because these two foldmethods are fast enough to dispense with FastFold, that is, they do not need to be artificially set to manual.

**Comment by fedorenchik** [comment]
The main advantage in this case is that folds don't get screwed (automatically opened) when you edit file in Insert mode. IMO, this is also very important.

**Comment by Konfekt** [comment]
I do not understand, when I enter insert mode outside of a fold in a file with `fdm=marker` in Vim 8.1589, then all folds stay closed.

**Comment by fedorenchik** [comment]
I mean, for example, with `fdm=marker` in a file with all folds closed, when you insert `{{{`, all folds below current line are automatically opened.

**Comment by Konfekt** [comment]
Ok, the latest commit adds a `g:fastfold_force` variable to suit this need. Tell us how it works out for you.

**Comment by fedorenchik** [comment]
It works great, thank you!

**Pull request closed without merging**
