### PR TITLE
Improve VimEnter autocmd

### PR DESCRIPTION
**Pull request by Shougo**
Hi, Thank you for the good plugin.
I have improved the behavior.
Please check it.

Note:  I will refactor your plugin after that...

### CODE REVIEW

**Comment by Konfekt** [comment]
Hey @Shougo, looks good to me. Could you explain, in the commit message, what's better about setting up `augroup FastFold` before `VimEnter`? Isn't then 

https://github.com/Shougo/FastFold/blob/VimEnter/plugin/fastfold.vim#L153

superfluous (overwriting`augroup FastFold`)?

**Comment by Shougo** [comment]
> Could you explain, in the commit message, what's better about setting up augroup FastFold before VimEnter?

OK.  I will explain it.
It is because, to enable lazy load using neobundle.
neobundle can call VimEnter autocommand in FastFold.
But neobundle cannot know which VimEnter autocommand is FastFold's without the augroup.
I think all plugins should define augroup including VimEnter autocommand.

**Comment by Konfekt** [comment]
Ok, if the commit message could reflect that: that is, add: 
```
to enable lazy load using neobundle.
neobundle can call VimEnter autocommand in FastFold.
But neobundle cannot know which VimEnter autocommand is FastFold's without the augroup...
```
Don't know how to do that once merged.

**Comment by Shougo** [comment]
Thank you!
Modified the commit message.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
